version: "3"

services:
  nodejs:
    build: 
      context: ./nodejs
    container_name: "nodejs"
    volumes:
      - ./nodejs:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - "db"
      - "rabbitmq"
    
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes: 
      - ../rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=08162200
    container_name: "rabbitmq"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./nodejs/.env
    ports:
      - "3306:3306"
    volumes:
      - ../mysql-data:/var/lib/mysql
    container_name: "db"